# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ This file is only read once per server start. Restart server when changed! ║
# ╚════════════════════════════════════════════════════════════════════════════╝

# Site settings
# ─────────────
baseurl: /1718-3CMO-BaP-nomivang
# host   : 127.0.0.1
# port   : 4000

# Custom Site variables
# ─────────────────────
title: Huisstijlgids VVW
description: "Online huisstijlgids van de Vlaamse Vereniging voor Weerkunde. Deze gids dient als leidraad voor alle visuele communicatie van de VVW zodat deze een herkenbare visuele samenhang vertoont."
tagline: "VVW | Huisstijlgids"

# Build settings
# ──────────────
defaults:
  -
#    scope:
#      path: "style-guide"
    values:
      layout: vertical

exclude:
  - Gemfile
  - README.md

plugins:
# - jekyll-feed
# - jekyll-gist
# - jekyll-mentions
# - jekyll-paginate
# - jekyll-redirect-from
# - jekyll-seo-tag
# - jekyll-sitemap
# - jemoji

sass:
  style: nested
#  style: expanded
#  style: compact
#  style: compressed
